/* Drogaria: conferência documental, persistência e integração com o gerador vigente.
 * Somente dados confirmados; fotos são evidências independentes do texto.
 */
(() => {
  'use strict';
  if (window.DrogariaReview) return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9);
  const api=()=>window.DrogariaAPI;
  const box=(s,n)=>((s.meta.drogaria_secoes||={})[n]||={answers:{},fields:{},docs:[],items:[]});
  const save=(fn,render=true)=>{const s=structuredClone(api().getState());fn(s);api().setState(s,{render});};
  const titles={area_geral:'Condições gerais',area_recebimento:'4.1 Área de recebimento de produtos',area_dispensacao:'4.2 Área de dispensação',area_armazenamento:'4.3 Área de armazenamento',area_residuos:'4.4 Armazenamento temporário de resíduos',area_vencidos:'4.5 Produtos vencidos ou violados',area_dml:'4.6 Depósito de material de limpeza',area_refeitorio:'4.7 Refeitório',area_sanitarios:'4.8 Vestiários e sanitários',termolabeis:'Medicamentos termolábeis',controlados_complementos:'Documentos e conferências',servicos_farmaceuticos:'Serviços farmacêuticos',documentos_qualidade:'8.1 Documentos de qualidade',documentos_rastreabilidade:'8.2 Rastreabilidade',documentos_remota:'8.3 Solicitação remota',documentos_descarte:'8.4 Descarte de medicamentos',transporte:'Transporte'};
  const cardOf=n=>n.startsWith('area_')?2:n==='termolabeis'?3:n==='controlados_complementos'?4:n==='servicos_farmaceuticos'?5:n.startsWith('documentos_')?6:n==='transporte'?8:Number(n.split('_')[1])||1;
  // Só equivalências de requisitos já existentes; não cria fundamento por semelhança.
  const mapped={
    'area_recebimento|conferencia':'receiving_exam','area_vencidos|segregacao':'quarantine',
    'area_dml|armazenamento':'dml_ok','area_refeitorio|separado':'break_room',
    'area_dispensacao|genericos':'generics','area_dispensacao|mips':'mip_grouped',
    'servicos_farmaceuticos|ambiente':'service_room','servicos_farmaceuticos|lavatório':'service_sink',
    'servicos_farmaceuticos|primeiros_socorros':'service_firstaid','servicos_farmaceuticos|limpeza':'service_clean',
    'servicos_farmaceuticos|rede_publica':'service_lista_saude','servicos_farmaceuticos|declaracao':'service_decl',
    'documentos_qualidade|criterios':'review_supplier_criteria','documentos_qualidade|distribuidores':'review_supplier_origin',
    'documentos_rastreabilidade|procedimento':'quality_trace'
  };
  const coreAnswers={'controlados_complementos|sngpc':'sngpc_adesao','controlados_complementos|transmissao':'sngpc_current','controlados_complementos|estoque':'stock_match','documentos_qualidade|treinamentos':'doc_training','documentos_descarte|pgrss':'doc_pgrss'};
  const extraCore={
    review_supplier_criteria:{refs:['rdc-44-2009::artigo::31'],frase_positiva:'O estabelecimento documenta e implementa critérios para garantir a origem e a qualidade dos produtos adquiridos.',frase_negativa:'O estabelecimento não documenta ou não implementa critérios para garantir a origem e a qualidade dos produtos adquiridos.',gera_irregularidade:true},
    review_supplier_origin:{refs:['rdc-44-2009::artigo::31::paragrafo::1'],frase_positiva:'A aquisição é realizada por distribuidores legalmente autorizados e licenciados.',frase_negativa:'A aquisição não é realizada exclusivamente por distribuidores legalmente autorizados e licenciados.',gera_irregularidade:true}
  };
  const informational=new Set(['comercializa','realiza','aplica','outra_uf','termolabeis','proprio','terceirizada','modelo','fracionamento','orientou_reset','caixa_agua','ar_condicionado']);
  function enabled(n,s){const sec=s.meta.drogaria_secoes||{};if(n==='servicos_farmaceuticos')return sec[n]?.answers.realiza==='sim';if(n==='documentos_remota')return sec[n]?.answers.realiza==='sim';if(n==='transporte')return sec[n]?.answers.aplica==='sim';if(n==='termolabeis')return s.answers.thermo==='sim';return true;}
  function sync(s) {
    // Capture semantic labels while the actual section is on screen. Persist them
    // with the draft so a report after reload does not depend on revisiting screens.
    const specs=s.meta.review_specs||={};
    document.querySelectorAll('[data-af-answer],[data-sd-answer],[data-fb-answer],[data-af-field],[data-af-text],[data-af-check],[data-sd-field],[data-sd-text],[data-sd-check],[data-fb-field],[data-fb-text],[data-fb-check]').forEach(el=>{
      const attr=[...el.attributes].find(a=>/^data-(af|sd|fb)-(answer|field|text|check)$/.test(a.name));if(!attr)return;
      const [n,k]=attr.value.split('|');if(!n||!k)return;
      const q=el.closest('.q'),label=q?.querySelector('.q-title')?.textContent||el.closest('label')?.querySelector('span')?.textContent;
      if(!label)return;
      specs[n+'|'+k]={label:label.trim(),group:attr.name.endsWith('answer')?'answers':'fields',refs:q?[...q.querySelectorAll('[data-law]')].map(x=>x.dataset.law):[]};
    });
    const sec=s.meta.drogaria_secoes||{};
    const controls=sec.controlados_complementos;
    if(controls){const f=controls.fields;if(['portaria344','c2','cannabis','antimicrobianos','glp1'].some(k=>Object.hasOwn(f,k))){s.fields.products=(s.fields.products||[]).filter(x=>!['controlado','antibiotico','glp1','cannabis'].includes(x));if(f.portaria344||f.c2)s.fields.products.push('controlado');if(f.antimicrobianos)s.fields.products.push('antibiotico');if(f.glp1)s.fields.products.push('glp1');if(f.cannabis)s.fields.products.push('cannabis');}}
    const sv=sec.servicos_farmaceuticos;
    if(sv?.answers.realiza){s.fields.services_defined=sv.answers.realiza==='sim'?'sim':'nao';const m={injetaveis:'injetaveis',lobulo:'lobulo',pressao:'pa',glicemia:'glicemia',temperatura:'temperatura'};s.fields.services=sv.answers.realiza==='sim'?Object.entries(m).filter(([k])=>sv.fields[k]).map(([,v])=>v):[];}
    if(sec.documentos_remota?.answers.realiza)s.fields.remote=sec.documentos_remota.answers.realiza;
    for(const [key,id] of Object.entries(coreAnswers)){const[n,k]=key.split('|'),v=sec[n]?.answers[k];if(v&&enabled(n,s))s.answers[id]=v;}
    s.meta.ultima_inspecao=s.meta.ultima_inspecao_periodo||s.meta.ultima_inspecao||'';
  }
  function photoScope(){const s=api().getState();if(!s.meta.inspecao_id)save(x=>x.meta.inspecao_id='drogaria_'+uid(),false);return api().getState().meta.inspecao_id;}
  function clearSection(s,card){for(const n of Object.keys(s.meta.drogaria_secoes||{}))if(cardOf(n)===card)delete s.meta.drogaria_secoes[n];for(const key of Object.keys(s.meta.review_specs||{}))if(cardOf(key.split('|')[0])===card)delete s.meta.review_specs[key];for(const obj of [s.notes,s.measures])for(const key of Object.keys(obj))if(key.startsWith('rev_')&&Object.keys(titles).some(n=>cardOf(n)===card&&key.startsWith('rev_'+n+'_')))delete obj[key];if(card===1){for(const k of ['cnpj','razao','fantasia','endereco','endereco_numero','bairro','municipio','cep','estado','cevs','lic_validade','cnae','afe','ae','atividade_licenciada','atividades_autorizadas','anvisa_consulta','data','inicio','fim','processo','finalidade','ultima_inspecao_periodo','ultima_inspecao','equipe','acompanhante','cargo','resp_legal','cpf_resp_legal','rt','crf','substituto','substituto_crf','funcionarios','farmaceuticos','horario_funcionamento','consideracoes_gerais','section1_documentos','licencas_especificas'])delete s.meta[k];delete s.fields.atividades_licenciadas;}if(card===4){s.fields.products=(s.fields.products||[]).filter(x=>!['controlado','antibiotico','glp1','cannabis'].includes(x));}if(card===5){s.fields.services=[];delete s.fields.services_defined;}if(card===6)delete s.fields.remote;}
  function dialog(title){let d=document.getElementById('drogaria-review');if(!d){d=document.createElement('dialog');d.id='drogaria-review';d.className='med-tools-dialog';document.body.append(d);}d.innerHTML='<header><h2>'+esc(title)+'</h2><button type="button" data-review-close>Fechar ×</button></header><div class="med-tools-body"></div>';d.querySelector('[data-review-close]').onclick=()=>d.close();return d;}
  function read({type,existing,onApply,section=''}) {
    const spec=window.DrogariaOcrTools.catalog[type];if(!spec)throw Error('Tipo de documento a definir com o usuário.');
    const scope=photoScope(),d=dialog(spec.title),body=d.querySelector('.med-tools-body');let result=null,file=null,preview='';
    body.innerHTML='<p>Fotografe ou selecione o documento. Confira e corrija os dados antes de aplicar. Campo não localizado permanece vazio.</p><div class="actions"><button type="button" data-cam>Fotografar documento</button><button type="button" data-file>Selecionar PDF, Word ou imagem</button><button type="button" data-manual>Preencher campos</button></div><input type="file" hidden accept="image/*" capture="environment" data-camera-input><input type="file" hidden accept="image/*,.pdf,.doc,.docx,.xml" data-file-input><p role="status"></p><div data-preview></div><div data-fields></div>';
    const status=t=>body.querySelector('[role=status]').textContent=t;
    const render=()=>{body.querySelector('[data-fields]').innerHTML='<div class="grid">'+Object.entries(result.fields).map(([k,v])=>'<label class="med-field">'+esc(k.replaceAll('_',' '))+'<textarea rows="2" data-value="'+esc(k)+'">'+esc(v)+'</textarea></label>').join('')+'</div><p>Não localizados: '+esc(Object.entries(result.fields).filter(([,v])=>!v).map(([k])=>k.replaceAll('_',' ')).join(', ')||'nenhum')+'.</p><details><summary>Texto lido</summary><pre>'+esc(result.rawText)+'</pre></details><label class="check"><input type="checkbox" data-report'+(result.includeInReport!==false?' checked':'')+'>Incluir os dados conferidos no texto do relatório</label>'+(file?.type.startsWith('image/')?'<label class="check"><input type="checkbox" data-keep>Guardar também esta fotografia como evidência da inspeção</label>':'')+'<p class="muted">Os campos ficam salvos para edição. O arquivo original não é anexado ao relatório. Fotografias só são mantidas como evidência quando você seleciona essa opção.</p><button type="button" class="primary" data-apply>Aplicar dados conferidos</button>';};
    const choose=async e=>{file=e.target.files[0];e.target.value='';if(!file)return;result=null;body.querySelector('[data-fields]').innerHTML='';if(preview)URL.revokeObjectURL(preview);preview=URL.createObjectURL(file);body.querySelector('[data-preview]').innerHTML=file.type.startsWith('image/')?'<img style="max-width:100%;max-height:240px" alt="Imagem original para conferência" src="'+preview+'">':'<a href="'+preview+'" target="_blank" rel="noopener">Visualizar arquivo original</a>';status('Lendo documento…');try{result=await window.DrogariaOcrTools.read(type,file,status);render();status('Confira antes de aplicar.');}catch(e){status(e.message);}};
    body.querySelector('[data-camera-input]').onchange=choose;body.querySelector('[data-file-input]').onchange=choose;
    body.querySelector('[data-cam]').onclick=()=>body.querySelector('[data-camera-input]').click();body.querySelector('[data-file]').onclick=()=>body.querySelector('[data-file-input]').click();
    body.querySelector('[data-manual]').onclick=()=>{result=window.DrogariaOcrTools.extract(type,'',{method:'Preenchimento manual conferido'});render();status('Preencha somente o que foi conferido no documento.');};
    body.addEventListener('click',async e=>{if(!e.target.matches('[data-apply]')||!result)return;const b=e.target;b.disabled=true;try{if(photoScope()!==scope)throw Error('A inspeção mudou. Abra novamente a leitura do documento.');body.querySelectorAll('[data-value]').forEach(x=>result.fields[x.dataset.value]=x.value.trim());result.includeInReport=body.querySelector('[data-report]').checked;if(body.querySelector('[data-keep]')?.checked){const p=await window.DrogariaOcrTools.fotos.save(scope,file,{section,caption:spec.title});window.DrogariaOcrTools.fotos.revokePreview(p);}await onApply(result);d.close();}catch(err){status(err.message);b.disabled=false;}});
    d.addEventListener('close',()=>{if(preview)URL.revokeObjectURL(preview);},{once:true});
    if(existing){result={documentType:type,documentTitle:existing.title||spec.title,fields:{...Object.fromEntries(spec.fields.map(k=>[k,''])),...existing.fields},rawText:existing.rawText||'',source:existing.source||{},includeInReport:existing.includeInReport};render();status('Dados salvos anteriormente. O arquivo original de leitura não foi mantido.');}
    d.showModal();
  }
  function readSection(n,type,id){const old=box(api().getState(),n).docs.find(x=>x.id===id);read({type,existing:old,section:titles[n]||n,onApply:r=>save(s=>{const b=box(s,n),doc={id:id||uid(),kind:type,title:r.documentTitle,fields:r.fields,rawText:r.rawText,source:r.source,includeInReport:r.includeInReport,readAt:new Date().toISOString()};const at=b.docs.findIndex(x=>x.id===id);if(at>=0)b.docs[at]=doc;else b.docs.push(doc);if(n==='transporte'&&type==='licenca_sanitaria'){const f=r.fields;b.fields.empresa=f.razao_social||b.fields.empresa;b.fields.cnpj=f.cnpj||b.fields.cnpj;b.fields.cevs=f.numero_cevs_ou_cmvs||b.fields.cevs;}})});}
  async function equipment(n,term){const value=String(term).replace(/\D/g,'');if(!value){alert('Informe o registro Anvisa ou processo.');return;}const d=dialog('Consultar equipamento'),body=d.querySelector('.med-tools-body');body.innerHTML='<p role="status">Consultando…</p>';d.showModal();try{const r=await window.DrogariaOcrTools.anvisa.equipamento(value.length>=12?{processo:value}:{registro:value});body.innerHTML='<p>'+r.results.length+' resultado(s). Selecione a apresentação correta e confira antes de aplicar.</p>'+r.results.map((x,i)=>'<button type="button" data-pick="'+i+'">'+esc([x.nome,x.fabricante,x.numero_anvisa_ou_processo].filter(Boolean).join(' · '))+'</button>').join('')+'<div data-details></div>';body.onclick=e=>{const pick=e.target.closest('[data-pick]');if(!pick)return;const x=r.results[Number(pick.dataset.pick)],detail=body.querySelector('[data-details]');detail.innerHTML='<p>'+esc(x.descricao)+'</p><label class="field"><span>Lote do equipamento (conferido no rótulo)</span><input data-lot></label><button type="button" data-add-equipment>Aplicar equipamento conferido</button>';detail.querySelector('[data-add-equipment]').onclick=()=>{save(s=>{const b=box(s,n);(b.items||=[]).push({id:uid(),nome:x.nome,fabricante:x.fabricante,descricao:x.descricao,registro:x.numero_anvisa,processo:x.processo,lote:detail.querySelector('[data-lot]').value,source:r.source,queriedAt:r.queriedAt});});d.close();};};}catch(e){body.textContent=e.message;}}
  async function photos(section='Inspeção'){const scope=photoScope(),d=dialog('Fotografias da inspeção'),body=d.querySelector('.med-tools-body');let shown=[];body.innerHTML='<p>Registro de imagem, sem extração de texto. As fotos não entram automaticamente no relatório textual.</p><label class="field"><span>Legenda</span><input data-caption></label><div class="actions"><button data-camera>Fotografar</button><button data-select>Selecionar imagens</button><button data-book>Emitir documento com as fotos desta inspeção</button></div><input type="file" accept="image/*" capture="environment" hidden data-camera-file><input type="file" accept="image/*" multiple hidden data-images><p role="status"></p><div data-gallery></div>';const st=t=>body.querySelector('[role=status]').textContent=t;
    const refresh=async()=>{shown.forEach(window.DrogariaOcrTools.fotos.revokePreview);shown=await window.DrogariaOcrTools.fotos.list(scope);body.querySelector('[data-gallery]').innerHTML=shown.map(p=>'<figure><img style="max-width:220px;max-height:160px" alt="'+esc(p.caption||'Foto da inspeção')+'" src="'+p.previewUrl+'"><figcaption>'+esc(p.caption||p.section)+'</figcaption></figure>').join('');};
    const add=async e=>{try{for(const f of e.target.files){const p=await window.DrogariaOcrTools.fotos.save(scope,f,{section,caption:body.querySelector('[data-caption]').value});window.DrogariaOcrTools.fotos.revokePreview(p);}await refresh();st('Fotos salvas nesta inspeção.');}catch(e){st(e.message);}finally{e.target.value='';}};
    body.querySelector('[data-camera-file]').onchange=add;body.querySelector('[data-images]').onchange=add;body.querySelector('[data-camera]').onclick=()=>body.querySelector('[data-camera-file]').click();body.querySelector('[data-select]').onclick=()=>body.querySelector('[data-images]').click();body.querySelector('[data-book]').onclick=async()=>{try{const m=api().getState().meta;await window.DrogariaOcrTools.fotos.downloadPhotoBook(scope,{establishment:m.razao,inspectionDate:m.data});}catch(e){st(e.message);}};d.addEventListener('close',()=>shown.forEach(window.DrogariaOcrTools.fotos.revokePreview),{once:true});d.showModal();await refresh();}
  function customRecords(cat,s,bank){const out=[],specs=s.meta.review_specs||{};for(const[n,b] of Object.entries(s.meta.drogaria_secoes||{})){if(!enabled(n,s))continue;for(const[k,v] of Object.entries(b.answers||{})){const spec=specs[n+'|'+k];if(!spec||!v||v==='nsa'||coreAnswers[n+'|'+k])continue;if(n==='controlados_complementos'&&k==='mapas72'&&b.answers.outra_uf!=='sim')continue;const core=cat.perguntas.find(q=>q.id===mapped[n+'|'+k])||extraCore[mapped[n+'|'+k]];const refs=core?.refs||spec.refs||[],issues=refs.map(id=>api().engine.refStatus(id,cat,bank,s)).filter(Boolean);const requirement=!informational.has(k),validated=!!core&&core.gera_irregularidade&&refs.length&&!issues.length;const phrase=core?(v==='sim'?core.frase_positiva:core.frase_negativa):spec.label.replace(/[?.]$/,'')+': '+(v==='sim'?'sim':'não')+'.';const id='rev_'+n+'_'+k;out.push({id,id_pergunta:id,card:cardOf(n),grupo:titles[n]||n,resposta:v,refs,norma:core?.norma||[],dispositivo:core?.dispositivo||[],frase_relatorio:phrase,observacao:s.notes[id]||'',irregularidade_gerada:v==='nao'&&validated,documento_pendente:false,documento_apresentado:false,pendencia_fundamento:v==='nao'&&requirement&&!validated?'Conferir o requisito e o dispositivo aplicável antes de enquadrar este achado.':'',medida:s.measures[id]||null,reviewSection:n});}}return out;}
  function appendDocs(B,docs){for(const d of docs||[]){if(d.includeInReport===false)continue;const text=Object.entries(d.fields||{}).filter(([,v])=>String(v??'').trim()).map(([k,v])=>k.replaceAll('_',' ')+': '+v).join('; ');if(text)B.push({t:'p',x:d.title+' — '+text+'.'});}}
  function orderDocumentSections(B){const start=B.findIndex(b=>b.t==='h1'&&/^8\s/.test(b.x));if(start<0)return B;let end=B.findIndex((b,i)=>i>start&&b.t==='h1'&&/^(9|10)\s/.test(b.x));if(end<0)end=B.length;const groups={'8.1':[],'8.2':[],'8.3':[],'8.4':[]},labels={'8.1':'8.1 Documentos de qualidade','8.2':'8.2 Rastreabilidade de medicamentos sujeitos a controle especial','8.3':'8.3 Solicitação remota','8.4':'8.4 Descarte de medicamentos e resíduos'};let key='8.1';for(const b of B.slice(start+1,end)){const heading=/^8\.[1-4](?:\s|$)/.exec(b.x||'');if(['h1','h2'].includes(b.t)&&heading){key=heading[0].trim();continue;}groups[key].push(b);}const ordered=[B[start]];for(const[k,rows]of Object.entries(groups))if(rows.length)ordered.push({t:'h2',x:labels[k]},...rows);return [...B.slice(0,start),...ordered,...B.slice(end)];}
  function report(original,cat,s,bank){
    // Work on a copy: generating a report must not modify the inspection.
    const state=structuredClone(s),sec=state.meta.drogaria_secoes||{};
    for(const ev of Object.values(state.evidence||{}))if(ev.includeInReport===false){delete ev.campos;delete ev.texto;}
    const base=original(cat,state,bank),B=[],chunks={};let key='intro';
    for(const b of base.blocks){if(b.t==='h1'&&/^\d+\s/.test(b.x))key=b.x.match(/^\d+/)[0];(chunks[key]||=[]).push(b);}
    const p=x=>{if(x)B.push({t:'p',x});},h=x=>B.push({t:'h1',x}),kv=(k,v)=>{if(v!==''&&v!=null)B.push({t:'kv',k,v:String(v)});};
    B.push(...(chunks.intro||[]));h('1 IDENTIFICAÇÃO DA EMPRESA');const m=state.meta;
    [['Razão social',m.razao],['Nome fantasia',m.fantasia],['CNPJ',m.cnpj],['Endereço',[m.endereco,m.endereco_numero,m.bairro,m.municipio,m.estado,m.cep].filter(Boolean).join(', ')],['Responsável legal',[m.resp_legal,m.cpf_resp_legal].filter(Boolean).join(' — CPF ')],['Responsável técnico',[m.rt,m.crf].filter(Boolean).join(' — CRF ')],['Responsável técnico substituto',[m.substituto,m.substituto_crf].filter(Boolean).join(' — CRF ')],['Licença sanitária CEVS / CMVS',m.cevs],['Validade da licença',api().engine.fmtDate(m.lic_validade)],['CNAE',m.cnae],['Atividades licenciadas (licença sanitária)',(state.fields.atividades_licenciadas||[]).join('; ')],['AFE',m.afe],['AE',m.ae],['Atividades autorizadas (Anvisa)',(m.atividades_autorizadas||[]).join('; ')]].forEach(([k,v])=>kv(k,v));
    B.push(...(chunks['2']||[]));h('3 CONSIDERAÇÕES GERAIS');p('Trata-se de um comércio varejista de produtos farmacêuticos sem manipulação de fórmulas (CNAE 4771-7/01).');kv('Horário de funcionamento',m.horario_funcionamento);kv('Funcionários',m.funcionarios);kv('Farmacêuticos',m.farmaceuticos);p(m.consideracoes_gerais);
    const records=base.records.filter(r=>!(r.card===5&&!enabled('servicos_farmaceuticos',state))&&!(r.card===8&&!enabled('transporte',state))&&!(['vaccine','eac'].includes(r.id)&&r.resposta==='nao'));
    records.filter(r=>r.card===1&&r.frase_relatorio&&!['vaccine','eac'].includes(r.id)).forEach(r=>p(r.frase_relatorio));appendDocs(B,m.section1_documentos);
    const custom=customRecords(cat,state,bank);records.push(...custom);
    function section(n){const b=sec[n];if(!b||!enabled(n,state))return;const rs=custom.filter(r=>r.reviewSection===n),specs=m.review_specs||{};const values=Object.entries(b.fields||{}).filter(([k,v])=>specs[n+'|'+k]&&v!==false&&v!==''&&v!=null&&!/busca|active/.test(k));if(!rs.length&&!values.length&&!b.docs?.length&&!b.items?.length)return;B.push({t:'h2',x:titles[n]||n});rs.forEach(r=>p(r.frase_relatorio+(r.observacao?' '+r.observacao:'')));values.forEach(([k,v])=>kv(specs[n+'|'+k].label,v===true?'Verificado':v));appendDocs(B,b.docs);for(const x of b.items||[])p([x.nome,x.fabricante,x.descricao,x.registro&&'registro Anvisa '+x.registro,x.processo&&'processo '+x.processo,x.lote&&'lote '+x.lote].filter(Boolean).join('; ')+'.');}
    B.push(...(chunks['4']||[]));['area_geral','area_recebimento','area_dispensacao','area_armazenamento','area_residuos','area_vencidos','area_dml','area_refeitorio','area_sanitarios'].forEach(section);
    if(state.answers.thermo==='sim')B.push(...(chunks['5']||[]));else if(state.answers.thermo==='nao'){h('5 MEDICAMENTOS TERMOLÁBEIS');p('O estabelecimento não realiza venda de medicamentos termolábeis.');}
    B.push(...(chunks['6']||[]));section('controlados_complementos');
    if(enabled('servicos_farmaceuticos',state)){B.push(...(chunks['7']||[]));section('servicos_farmaceuticos');}
    B.push(...(chunks['8']||[]));['documentos_qualidade','documentos_rastreabilidade','documentos_remota','documentos_descarte'].forEach(section);
    if(enabled('transporte',state)){h('9 TRANSPORTE');section('transporte');}else if(['nao','nsa'].includes(sec.transporte?.answers.aplica)){h('9 TRANSPORTE');p('Transporte e entrega domiciliar não se aplicam ao estabelecimento.');}
    h('10 DOCUMENTAÇÃO');const allDocs=[...(m.section1_documentos||[]),...Object.entries(sec).filter(([n])=>enabled(n,state)).flatMap(([,b])=>b.docs||[])].filter(d=>d.includeInReport!==false);allDocs.forEach(d=>p([d.title,d.fields?.nome_funcionario,d.fields?.numero_certificado||d.fields?.numero_certidao||d.fields?.numero_nota].filter(Boolean).join(' — ')));Object.entries(sec).filter(([n])=>n.startsWith('native_')&&enabled(n,state)).forEach(([,b])=>appendDocs(B,b.docs));const pending=records.filter(r=>r.documento_pendente);if(pending.length){B.push({t:'h2',x:'Documentação pendente'});pending.forEach(r=>p(r.documento||r.frase_relatorio));}
    // Same records feed Word, HTML, print and the native findings/measures screen.
    const irregularities=records.filter(r=>r.irregularidade_gerada),legalPending=records.filter(r=>r.pendencia_fundamento);
    h('11 IRREGULARIDADES OBSERVADAS');irregularities.forEach((r,i)=>B.push({t:'num',n:i+1,x:r.frase_relatorio+(r.observacao?' '+r.observacao:'')+' Fundamento: '+r.refs.map(id=>{const q=cat.referencias[id];return q.norma+', '+q.dispositivo;}).join('; ')+'.'}));if(!irregularities.length)p('Não foram registradas irregularidades com fundamento validado.');if(legalPending.length){B.push({t:'h2',x:'Achados com enquadramento pendente'});legalPending.forEach(r=>p(r.frase_relatorio+' '+r.pendencia_fundamento));}
    h('12 MEDIDAS ADOTADAS E DOCUMENTOS EMITIDOS');records.filter(r=>r.medida?.tipo).forEach(r=>p([r.medida.tipo,r.frase_relatorio,r.medida.numero&&'Documento nº '+r.medida.numero,r.medida.prazo&&'Prazo: '+r.medida.prazo+' dias',r.medida.detalhe].filter(Boolean).join(' — ')));
    h('13 CONSIDERAÇÕES FINAIS E AVALIAÇÃO DE RISCOS');kv('Avaliação de risco registrada pela equipe',state.risk);p(m.risk_reason);p(state.notes.geral);
    return {...base,blocks:orderDocumentSections(B),records,irregularities,pending,legalPending,answered:records.filter(r=>r.resposta).length,total:records.length};
  }
  let installed=false;
  function install(){if(installed)return;installed=true;const original=api().engine.report;api().engine.report=(cat,s,bank)=>report(original,cat,s,bank);
    if(window.MedTools?.photo)window.MedTools.photo=async(scope,id,done=()=>{})=>{await photos(String(id||'Inspeção'));await done();};
    // Resolve somente dispositivos existentes na cópia normativa, com a mesma
    // proveniência e hash usados pelo catálogo. Não altera o banco de legislação.
    const cat=api().getCatalog(),bank=api().getBank();
    for(const id of ['rdc-44-2009::artigo::10','rdc-44-2009::artigo::12','rdc-44-2009::artigo::31','rdc-44-2009::artigo::31::paragrafo::1','rdc-44-2009::artigo::61::paragrafo::3']){
      if(cat.referencias[id])continue;const file='legislacao_v12/normas/'+id.split('::')[0]+'.json',d=bank[file],nodes=d?.nos.filter(n=>n.id===id);if(nodes?.length===1){const n=nodes[0];cat.referencias[id]={arquivo:file,sha256_texto:d.sha256_texto,norma:d.norma,dispositivo:n.rotulo,fonte_oficial:d.proveniencia?.fonte_oficial};}
    }
    for(const id of ['vaccine_licensed','eac_licensed']){const q=cat.perguntas.find(x=>x.id===id);if(q){const name=id==='vaccine_licensed'?'vacinação':'EAC';q.pergunta='Possui licença sanitária específica para '+name+'?';q.frase_positiva='O estabelecimento informou possuir licença sanitária específica para '+name+'.';q.frase_negativa='O estabelecimento realiza '+name+' sem possuir licença sanitária específica.';}}
    document.addEventListener('click',e=>{const edit=e.target.closest('[data-review-edit]');if(edit){const[n,id]=edit.dataset.reviewEdit.split('|'),d=box(api().getState(),n).docs.find(x=>x.id===id);if(d)readSection(n,d.kind,id);return;}if(e.target.closest('[data-inspection-photos]')){photos();return;}const raw=e.target.closest('[data-ocr]');if(!raw)return;const val=raw.dataset.ocr;if(!val.startsWith('document:'))return;const[,,key]=val.split(':'),id=key?.split('@')[0];const types={doc_lfs:'licenca_sanitaria',doc_crt:'certidao_regularidade_crf',doc_aso:'aso',doc_pragas:'controle_pragas_urbanas',doc_therm_cal:'calibracao_termohigrometro',doc_cold_cal:'calibracao_termohigrometro',doc_cold_pop:'pop_manual_pgrss',doc_receiving_pop:'pop_manual_pgrss',doc_sngpc_cert:'sngpc_escrituracao_digital',sngpc_current:'sngpc_transmissao_regular',doc_bmpo_trim:'comprovante_mapas_balancos',doc_mbpf:'pop_manual_pgrss',doc_pgrss:'pop_manual_pgrss',doc_service_pop:'pop_manual_pgrss',doc_remote_pop:'pop_manual_pgrss',doc_invoice:'danfe_nfe'};const type=types[id];if(!type)return;e.preventDefault();e.stopImmediatePropagation();if(['doc_lfs','doc_crt','doc_aso'].includes(id)){window.DrogariaSection1.reviewDocument(type);return;}const q=api().getCatalog().perguntas.find(x=>x.id===id),n='native_'+(q?.card||1);read({type,section:q?.pergunta,onApply:r=>save(s=>{s.evidence[key]={...(s.evidence[key]||{}),campos:r.fields,texto:r.rawText,arquivo:r.source?.filename,includeInReport:r.includeInReport};box(s,n).docs.push({id:uid(),kind:type,title:r.documentTitle,fields:r.fields,source:r.source,rawText:r.rawText,includeInReport:r.includeInReport});})});},true);
    const mountPhotos=()=>{const content=document.getElementById('content');if(content&&!content.querySelector('[data-inspection-photos]')){const b=document.createElement('button');b.type='button';b.dataset.inspectionPhotos='';b.className='no-print';b.textContent='Fotografias da inspeção · registrar / emitir documento';content.prepend(b);}};mountPhotos();new MutationObserver(mountPhotos).observe(document.getElementById('content'),{childList:true});
  }
  window.DrogariaReview={sync,install,read,readSection,equipment,photos,photoScope,report,customRecords,clearSection};
})();
