/* ——— Para saber mais: conceitos e referências técnicas ———
   Apoio ao inspetor nos módulos do núcleo de medicamentos. Não é norma: não
   capitula infração, não vira citação e não entra no relatório. Traz o
   conceito por trás da verificação e a referência técnica usual (Farmacopeia,
   ABNT, OMS, USP), para contextualizar a conversa com o responsável técnico.
   Uso: SaberMais.html(modulo, chave) → <details> ou ''. */
(function(){
 if(window.SaberMais)return;
 const S={
 manip:{
  'i3.2':[['Saúde ocupacional','O ASO é emitido dentro do PCMSO (NR-7). Quem manipula hormônios, antibióticos, citostáticos ou imunossupressores está exposto a agentes de risco, e o PCMSO deve prever exames específicos para essa exposição. A NR-32 trata da segurança do trabalhador em serviços de saúde, inclusive do manuseio de medicamentos perigosos.']],
  'i4.1':[['Classificação dos resíduos','Resíduo de medicamento, de matéria-prima vencida e de embalagem contaminada com fármaco é do Grupo B (químico) na RDC 222/2018. A periculosidade de cada substância está na FDS (ficha com dados de segurança, ABNT NBR 14725). A ABNT NBR 10004 classifica resíduos sólidos em perigosos e não perigosos.'],['Logística reversa','Medicamentos domiciliares vencidos ou em desuso devolvidos pela população seguem o sistema de logística reversa do Decreto nº 10.388/2020, separado do resíduo gerado pela própria farmácia.']],
  'i5.8':[['Faixas de armazenamento (Farmacopeia Brasileira)','Temperatura ambiente: 15 a 30 °C. Local fresco: 8 a 15 °C. Refrigerador: 2 a 8 °C. A umidade não tem limite geral: segue a especificação do fabricante e a natureza da substância. Higroscópicas pedem recipiente bem fechado e, quando indicado, dessecante; fotossensíveis, recipiente âmbar ou opaco.'],['Situação da matéria-prima','Quarentena, aprovado e reprovado são estados documentados, não apenas lugares: o rótulo interno e o registro do controle de qualidade devem dizer o mesmo. A saída segue o critério de vencimento (primeiro que vence, primeiro que sai — FEFO), não só a ordem de chegada.']],
  'i6.2':[['Referência analítica','A Farmacopeia Brasileira é o código oficial. Quando ela não tiver monografia, podem ser usadas farmacopeias estrangeiras admitidas pela Anvisa (RDC nº 511/2021). O certificado do fornecedor não dispensa os ensaios da farmácia: ele é conferido contra a especificação e contra o que a farmácia mede.'],['Ensaios típicos de recebimento','Características organolépticas, solubilidade, pH, peso, volume, ponto de fusão e densidade, conforme a matéria-prima. O objetivo é confirmar identidade e detectar troca ou degradação, não repetir toda a monografia.']],
  'i6.3':[['Calibração e verificação da balança','Calibração é feita por laboratório acreditado (RBC/Inmetro) e gera certificado com a incerteza de medição. Verificação é a checagem de rotina com pesos-padrão, feita pela farmácia e registrada. As duas são necessárias: o certificado não substitui a verificação do dia.'],['Carga mínima','Toda balança tem uma massa abaixo da qual o erro relativo fica grande demais (conceito de carga mínima ou “minimum weight”, USP <41> e <1251>). Pesar microgramas de fármaco de baixa dose numa balança de faixa alta é o erro clássico: por isso existem as diluições padronizadas.'],['Local da pesagem','Mesa estável, nivelada, longe de corrente de ar e de vibração, com exaustão que não perturbe a leitura.']],
  'i6.4':[['Água purificada','A monografia da Farmacopeia controla condutividade e carbono orgânico total (COT), além da pureza microbiológica (limite usual de 100 UFC/mL). Na manipulação, a água usada deve ter menos de 24 horas desde a produção, ou ser armazenada em condições que impeçam proliferação.'],['Sistema','Osmose reversa, deionização e lâmpada UV dependem de manutenção: troca de resinas e carvão, sanitização periódica e registro. Ponto de coleta para análise é o ponto de uso, não a saída do equipamento.']],
  'i6.5':[['Diluição geométrica','Para misturar pequena quantidade de fármaco com grande quantidade de excipiente: mistura-se o fármaco com volume igual de excipiente e, a cada etapa, dobra-se o volume até incorporar todo o diluente. Garante homogeneidade em doses baixas.'],['Fator de correção','A massa pesada corrige a diferença entre sal e base (fator de equivalência), o teor declarado no certificado e a água ou umidade quando a especificação for na base seca. O cálculo deve estar na ordem de manipulação.'],['Escolha da cápsula','A cápsula é escolhida pelo volume do pó, não pela massa. Volumes aproximados: nº 000 1,37 mL; 00 0,95 mL; 0 0,68 mL; 1 0,50 mL; 2 0,37 mL; 3 0,30 mL; 4 0,21 mL.']],
  'i7.1':[['Baixo índice terapêutico','São fármacos com pequena distância entre dose eficaz e dose tóxica: um erro pequeno de pesagem ou de homogeneidade tem efeito clínico. Por isso a norma exige dupla checagem, diluições padronizadas registradas e monitoramento de teor e uniformidade.']],
  'i7.2':[['Contenção','Salas de hormônios, antibióticos e citostáticos existem para proteger o produto e as pessoas: antecâmara, pressão negativa em relação às áreas adjacentes e exaustão com filtro impedem que o pó saia da sala. Equipamentos e utensílios exclusivos evitam contaminação cruzada.'],['Medicamentos perigosos','A lista do NIOSH (EUA) de medicamentos perigosos em serviços de saúde é a referência técnica usual para classificar o risco de exposição ocupacional e definir EPI.']],
  'i7.5':[['Citostáticos','Além das exigências da sala, a NR-32 trata do preparo de quimioterápicos antineoplásicos: EPI, capacitação, procedimentos para derramamento e descarte como resíduo químico perigoso.']],
  'i7.6':[['Referência','A Farmacopeia Homeopática Brasileira (3ª edição) define métodos de preparo, escalas (decimal, centesimal e cinquenta milesimal), insumos inertes e teores alcoólicos. O alcoômetro confere o grau do insumo líquido; a vidraria reutilizada passa por processo de inativação descrito em procedimento.']],
  'i8.1':[['Qualificação','Qualificação de instalação (QI), de operação (QO) e de desempenho (QD) respondem a perguntas diferentes: foi instalado como projetado, funciona nas faixas especificadas, e controla o pó na rotina real. Após mudança relevante ou no prazo definido, há requalificação.'],['Captação localizada','A eficácia depende da velocidade do ar na boca do captor e da distância até a fonte de pó. A ABNT NBR 16401 trata de instalações de ar-condicionado; para captação localizada, o manual de ventilação industrial da ACGIH é a referência técnica usual.']],
  'i9.1':[['Receituários','Portaria SVS/MS nº 344/1998: Notificação de Receita A (amarela) para entorpecentes; B (azul) e B2 para psicotrópicos e anorexígenos; Receita de Controle Especial em duas vias para as listas C1 e C5. Antimicrobianos seguem a RDC nº 471/2021: receita válida por 10 dias, com retenção da segunda via.']],
  'i9.2':[['Ordem de manipulação','É o documento que liga a prescrição ao produto: fármacos, concentrações, lotes das matérias-primas, cálculos com fatores de correção, quantidades pesadas, conferência e aprovação do farmacêutico. É o ponto de partida da rastreabilidade.']],
  'i10.1':[['Rastreabilidade ascendente e descendente','Ascendente: do produto entregue aos lotes de matéria-prima, fornecedor e certificado. Descendente: de um lote de matéria-prima a todos os pacientes que receberam fórmulas com ele. A amostragem testa as duas direções.']],
  'i10.2':[['Prazo de uso','Na ausência de estudo próprio, o prazo de uso de manipulados costuma seguir literatura como a USP <795> (revisão 2023): aquosas sem conservante, 14 dias refrigeradas; aquosas com conservante, 35 dias; líquidos orais não aquosos, 90 dias; demais formas não aquosas e sólidas, 180 dias. O prazo adotado deve estar justificado no procedimento.'],['Compatibilidade','Base e ativo precisam ser compatíveis: carga (aniônico × catiônico), faixa de pH de estabilidade do fármaco e do conservante.']],
  'i10.3':[['Conservação','Em líquidos, a eficácia do conservante depende do pH e da compatibilidade com o ativo. O pH medido é também um indicador de erro de preparo.']],
  'i11.1':[['Pureza microbiológica','A amostragem deve ser asséptica e representativa do ponto de uso. O resultado é expresso em UFC por mL ou g e comparado ao limite da monografia; tendência crescente, mesmo dentro do limite, pede investigação do sistema.']],
  'i11.2':[['Uniformidade de conteúdo','Mede quanto cada unidade se afasta do valor declarado. No ensaio farmacopeico de uniformidade de doses unitárias, o critério é o valor de aceitação (VA ≤ 15,0 no primeiro estágio). Doses baixas são o maior risco, por isso a prioridade abaixo de 5 mg.']],
  'i11.4':[['Água potável','O padrão de potabilidade é o da Portaria GM/MS nº 888/2021: ausência de coliformes totais e Escherichia coli em 100 mL, cloro residual livre mínimo de 0,2 mg/L e demais parâmetros físico-químicos. A limpeza da caixa d’água é semestral e registrada.']],
  'i11.5':[['Laboratório contratado','Laboratórios da REBLAS são habilitados pela Anvisa e seguem as Boas Práticas para Laboratórios Analíticos (RDC nº 1.039/2026), com sistema de gestão pela ABNT NBR ISO/IEC 17025.']],
  'i12.2':[['Transporte de termossensíveis','Embalagem térmica passiva (caixa isotérmica com gelo reutilizável) só mantém a faixa pelo tempo e na configuração em que foi testada. Gelo em contato direto com o produto pode congelar formulações refrigeradas.']]
 },
 dist:{
  'armazenamento':[['Faixas e zona climática','Farmacopeia Brasileira: ambiente 15 a 30 °C; refrigerado 2 a 8 °C. O Brasil está na zona climática IVb (30 °C / 75% UR) para estudos de estabilidade (RDC nº 318/2019): por isso a especificação do detentor do registro é o parâmetro de armazenagem.'],['FEFO','A expedição segue o vencimento (primeiro que vence, primeiro que sai), controlado pelo sistema e por endereçamento, não pela posição física do palete.'],['Temperatura cinética média (MKT)','Resume numa só temperatura o efeito de uma série de leituras sobre a degradação do produto. Ajuda a avaliar excursões curtas, mas não substitui a análise de cada excursão contra os dados de estabilidade do fabricante.']],
  'qt-area':[['Mapeamento térmico','O guia da OMS (TRS 961, Anexo 9, Suplemento 8) recomenda mapear a área vazia e carregada, no verão e no inverno, por pelo menos 7 dias contínuos, com sensores em grade nas três dimensões e nos pontos críticos (portas, teto, próximo a fontes de calor). O resultado define onde ficam os sensores de rotina.']],
  'termolabeis':[['Cadeia fria','Produto de 2 a 8 °C não pode congelar nem aquecer: congelamento costuma ser irreversível para insulinas e vacinas. Refrigerador doméstico não é equipamento qualificado para armazenagem profissional; câmaras e refrigeradores farmacêuticos têm controle, alarme e registro contínuo.'],['Falha de energia','O tempo que o equipamento mantém a faixa desligado (tempo de retenção) deve ser conhecido por estudo; ele define o plano de contingência e o prazo para acionar o gerador ou transferir a carga.']],
  'qt-equip':[['Qualificação de equipamentos','QI confirma a instalação; QO, o funcionamento vazio (setpoint, uniformidade, alarmes, abertura de porta); QD, o desempenho carregado na rotina. Sensores e registradores devem ter certificado de calibração rastreável (RBC).']],
  'transporte':[['Embalagem ativa e passiva','Ativa: temperatura controlada por equipamento (baú refrigerado). Passiva: caixa térmica com refrigerante, validada para uma configuração e um tempo. Perfis de temperatura externa como os da ISTA 7D são usados para testar embalagens passivas no verão e no inverno.']],
  'qt-veiculo':[['Veículo e embalagem','Um baú qualificado não qualifica a caixa térmica, e vice-versa: cada solução de transporte tem sua qualificação, feita na pior condição de carga e de clima.']],
  'qt-rota':[['Perfil de rota','O estudo registra a temperatura real do trajeto, com paradas, transbordos e portas abertas, nas estações extremas. É o que sustenta a dispensa de monitoramento contínuo prevista na RDC 430/2020.']],
  'recolhimento':[['Recolhimento','A RDC nº 55/2005 regula o recolhimento; a distribuidora participa na proporção do seu mapa de distribuição. A simulação anual testa, no pior caso da rede, se o mapa permite localizar e reconciliar as unidades em tempo.']],
  'desvios':[['Desvio, não conformidade e CAPA','Desvio é o afastamento de um procedimento ou especificação; a investigação busca a causa raiz (por exemplo, 5 porquês ou diagrama de Ishikawa) e define ação corretiva e preventiva (CAPA), com verificação de eficácia. Fechar o desvio sem causa raiz é o achado mais comum.']],
  'reclamacoes':[['Reclamação','Reclamação de qualidade (produto) vai ao detentor do registro para investigação; reclamação de serviço (atraso, avaria no transporte) é investigada pela própria empresa. Registrar as duas separadamente facilita a análise de tendência.']],
  'sistemas':[['Validação de sistemas','A abordagem usual é baseada em risco, com as categorias de software do GAMP 5 (ISPE). A integridade de dados segue o princípio ALCOA+: atribuível, legível, contemporâneo, original e exato, além de completo, consistente, durável e disponível.']],
  'qualificacao-sistemas':[['Trilha de auditoria','Em sistemas que registram lote, validade, temperatura ou liberação, a trilha de auditoria mostra quem alterou o quê e quando, e deve ser revisada periodicamente, não só existir.']],
  'fornecedores':[['Qualificação','Qualificar o fornecedor vai além de conferir AFE e licença: inclui avaliação da qualidade do serviço e, quando o risco justificar, auditoria. A consulta pública de AFE/AE mostra a situação na data consultada.']],
  'residuos':[['Medicamentos vencidos','O resíduo da própria empresa segue a RDC 222/2018 e o PGRSS. Medicamentos domiciliares devolvidos pela população entram na logística reversa do Decreto nº 10.388/2020.']],
  'ifa-rastreabilidade':[['CADIFA e CBPF','A CADIFA (RDC nº 359/2020) é a carta de adequação do dossiê do IFA, exigida no contexto do registro de medicamentos industrializados. O CBPF de IFA atesta boas práticas do fabricante do insumo. Nenhum dos dois, sozinho, comprova a qualidade de um lote: isso é papel do certificado de análise e da conferência de recebimento.'],['Fracionamento','Fracionar insumo é abrir a embalagem original: exige área adequada, rotulagem que preserve a identidade do fabricante e do lote e análise após o fracionamento (RDC nº 204/2006).']],
  'cq_atividades':[['Boas práticas de laboratório','A RDC nº 1.039/2026 remete os laboratórios de controle de qualidade de medicamentos ao guia da OMS (TRS 1052, Anexo 4, 2024). Nele estão os requisitos de equipamentos, água, reagentes, padrões, cepas e investigação de resultados.'],['Cepas de referência','A prática farmacopeica limita as culturas de trabalho a no máximo 5 passagens a partir da cepa de referência (ATCC ou equivalente), com registro de cada repique.']],
  'cq_padroes':[['Padrões','Padrão primário é o oficial (Farmacopeia Brasileira, USP, EP). Padrão secundário ou de trabalho é qualificado contra o primário, com certificado interno e prazo de reteste.']],
  'cq_oos':[['Resultado fora de especificação','A investigação começa no laboratório (erro analítico evidente?) e, sem causa laboratorial, passa ao processo. Retestar até “passar” sem justificativa não é permitido. A referência conceitual usual é o guia da FDA sobre investigação de OOS.']]
 },
 drog:[
  [/Termol/i,[['Faixa e controle','Refrigerado: 2 a 8 °C (Farmacopeia Brasileira). Termômetro de máxima e mínima calibrado, leitura registrada ao menos duas vezes ao dia, e a máxima e a mínima zeradas após cada leitura. Nada de medicamento na porta ou em contato com a parede do fundo.'],['Vacinação','Farmácia que vacina segue a RDC nº 197/2017: equipamento exclusivo para imunobiológicos e plano de contingência para falha de energia.']]],
  [/Dispensa|Armazenamento/i,[['Temperatura ambiente','Ambiente, pela Farmacopeia: 15 a 30 °C. O termo-higrômetro fica no local onde os medicamentos estão, e a leitura precisa ser registrada, não só existir.'],['Genéricos e MIPs','A intercambialidade do genérico vem da Lei nº 9.787/1999. Medicamento isento de prescrição (MIP) pode ficar ao alcance do usuário; os demais, não.']]],
  [/Controlad|Antimicrob/i,[['Receituários','Portaria SVS/MS nº 344/1998: Notificação A (amarela), B (azul) e Receita de Controle Especial em duas vias (C1, C5). Antimicrobianos: RDC nº 471/2021, receita válida por 10 dias e retenção da segunda via. A escrituração é feita no SNGPC.']]],
  [/Servi[çc]os/i,[['Serviços farmacêuticos','Aferição de pressão e glicemia, aplicação de injetáveis e outros serviços seguem a RDC nº 44/2009. Perfurocortantes vão para coletor rígido (ABNT NBR 13853) e, como resíduo, para o Grupo E da RDC 222/2018.']]],
  [/Res[íi]duo|vencid/i,[['Destino','Resíduo da drogaria segue a RDC 222/2018. Medicamento devolvido pela população entra na logística reversa (Decreto nº 10.388/2020), em coletor identificado, separado do estoque e dos vencidos da própria loja.']]],
  [/Venda remota|Transporte|entrega/i,[['Entrega de termolábeis','A caixa térmica só mantém 2 a 8 °C na configuração e pelo tempo em que foi testada. Gelo em contato com o produto pode congelar insulina.']]]
 ]
 };
 function esc(t){return String(t==null?'':t).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'})[c])}
 function caixa(itens){if(!itens||!itens.length)return '';return '<details class="sm-box"><summary>📘 Para saber mais — conceitos e referências técnicas</summary>'+itens.map(([t,p])=>'<p><b>'+esc(t)+'.</b> '+esc(p)+'</p>').join('')+'<p class="sm-nota">Apoio técnico. Não é norma, não gera irregularidade e não entra no relatório.</p></details>'}
 function html(mod,chave){if(mod==='drog'){const txt=String(chave||'');const m=S.drog.find(([re])=>re.test(txt));return caixa(m&&m[1])}return caixa((S[mod]||{})[chave])}
 const css='.sm-box{border:1px solid #cbd9c9;border-left:4px solid #4f7a52;border-radius:0 10px 10px 0;background:#f4f8f3;margin:8px 0;padding:0 12px}.sm-box>summary{cursor:pointer;padding:9px 0;font-weight:700;color:#2f5733;font-size:.84rem;list-style:none}.sm-box>summary::-webkit-details-marker{display:none}.sm-box p{margin:0 0 9px;font-size:.84rem;line-height:1.5;color:#26382a}.sm-box .sm-nota{font-size:.74rem;color:#5d6f60;border-top:1px dashed #cbd9c9;padding-top:6px}';
 function estilo(){if(document.getElementById('sm-style'))return;const s=document.createElement('style');s.id='sm-style';s.textContent=css;(document.head||document.documentElement).appendChild(s)}
 try{estilo()}catch(e){}
 window.SaberMais={html,dados:S,estilo};
})();
