# Frases do relatório de Manipulação v2: (Cumpre, Não cumpre) por pergunta.
# "Não se aplica" não gera texto. Perguntas informativas usam só a primeira frase.
F = {
 'r001': ('A licença sanitária e as autorizações da Anvisa (AFE/AE) correspondem às atividades exercidas.', 'A licença sanitária e/ou as autorizações da Anvisa (AFE/AE) não correspondem às atividades exercidas.'),
 'r002': ('Os grupos de atividade manipulados estão contemplados na licença sanitária.', 'Há grupo de atividade manipulado que não está contemplado na licença sanitária.'),
 'r003': ('Há Autorização Especial publicada em DOU para as atividades sujeitas a controle especial.', 'Manipula substâncias sujeitas a controle especial sem Autorização Especial publicada em DOU.'),
 'r021': ('A farmácia dispõe das áreas mínimas previstas, com infraestrutura adequada às atividades.', 'A farmácia não dispõe de todas as áreas mínimas previstas ou a infraestrutura não é adequada às atividades.'),
 'r027': ('A área de descanso/refeitório é separada dos demais ambientes.', 'A área de descanso/refeitório não é separada dos demais ambientes.'),
 # Documentação
 'r176': ('Apresentou Manual de Boas Práticas de Manipulação, com organograma e fluxograma.', 'Não apresentou Manual de Boas Práticas de Manipulação completo (com organograma e fluxograma).'),
 'r177': ('Apresentou Manual de Boas Práticas Farmacêuticas.', 'Não apresentou Manual de Boas Práticas Farmacêuticas.'),
 'r178': ('Apresentou PCMSO e registros dos exames médicos admissionais e periódicos.', 'Não apresentou PCMSO e/ou os registros dos exames médicos admissionais e periódicos.'),
 'r179': ('Apresentou o Programa de Gerenciamento de Riscos.', 'Recomenda-se apresentar o Programa de Gerenciamento de Riscos.'),
 'r180': ('Apresentou comprovante de limpeza da caixa d’água.', 'Não apresentou comprovante de limpeza da caixa d’água.'),
 'r182': ('Apresentou registros de manutenção e limpeza do sistema de climatização.', 'Não apresentou registros de manutenção e limpeza do sistema de climatização.'),
 'r184': ('A planta/croqui permite identificar as áreas e os sistemas de ar independentes.', 'A planta/croqui não permite identificar as áreas e os sistemas de ar independentes.'),
 'r185': ('Apresentou AVCB/CLCB.', 'Recomenda-se apresentar AVCB/CLCB vigente.'),
 'r065': ('Dispõe de Programa de Controle Integrado de Pragas e Vetores, executado por empresa licenciada, com registros.', 'Não apresentou Programa de Controle Integrado de Pragas e Vetores com os respectivos registros.'),
 'r190': ('As reclamações sobre desvio de qualidade são registradas, investigadas e respondidas.', 'Não há registro, investigação e resposta das reclamações sobre desvio de qualidade.'),
 'r191': ('As autoinspeções são anuais, documentadas, com ações corretivas.', 'Não há autoinspeção anual documentada, com ações corretivas.'),
 'r193': ('Apresentou qualificação de fornecedores, com avaliação de BPF/fracionamento/distribuição.', 'Não apresentou qualificação completa de fornecedores.'),
 'r195': ('Apresentou programa de manutenção preventiva de equipamentos, purificador, exaustores e ar-condicionado.', 'Não apresentou programa de manutenção preventiva dos equipamentos.'),
 'r201': ('Apresentou POP/ficha de especificação da água purificada e potável.', 'Não apresentou POP/ficha de especificação da água purificada e potável.'),
 # Treinamento
 'r016': ('Há programa de treinamento de todo o pessoal, elaborado com base em levantamento de necessidades.', 'Não há programa de treinamento de todo o pessoal elaborado com base em levantamento de necessidades.'),
 'r017': ('Todo o pessoal, inclusive de limpeza e manutenção, recebeu treinamento inicial e continuado.', 'Não foi comprovado treinamento inicial e continuado de todo o pessoal.'),
 'r018': ('Foram realizados treinamentos específicos para as atividades dos anexos exercidas.', 'Não foram comprovados treinamentos específicos para as atividades dos anexos exercidas.'),
 'r019': ('Os treinamentos incluem procedimentos em caso de acidente/incidente e informações sobre riscos.', 'Os treinamentos não incluem procedimentos em caso de acidente/incidente e informações sobre riscos.'),
 'r020': ('A efetividade dos treinamentos é avaliada.', 'A efetividade dos treinamentos não é avaliada.'),
 # Pessoal
 'r004': ('Possui organograma que demonstra estrutura organizacional e pessoal suficiente.', 'Não possui organograma que demonstre estrutura organizacional e pessoal suficiente.'),
 'r005': ('As atribuições e responsabilidades estão formalmente descritas.', 'As atribuições e responsabilidades não estão formalmente descritas.'),
 'r006': ('A admissão é precedida de exames médicos, com avaliações periódicas conforme o PCMSO.', 'Não foi comprovada a realização de exames médicos admissionais e periódicos.'),
 'r007': ('Há procedimento de afastamento de funcionário com lesão exposta ou enfermidade.', 'Não há afastamento de funcionário com lesão exposta ou enfermidade que possa comprometer a preparação.'),
 'r008': ('É observada a proibição de cosméticos, joias e adornos nas áreas de pesagem e manipulação.', 'Não é observada a proibição de cosméticos, joias e adornos nas áreas de pesagem e manipulação.'),
 'r009': ('É observada a proibição de comer, beber, fumar e manter objetos pessoais nas salas de pesagem e manipulação.', 'Foram encontrados alimentos, objetos pessoais ou medicamentos de uso pessoal nas salas de pesagem ou manipulação.'),
 'r010': ('Os empregados são instruídos a reportar condições de risco.', 'Os empregados não são instruídos a reportar condições de risco.'),
 'r011': ('O EPI é fornecido gratuitamente, em quantidade suficiente e com reposição periódica.', 'Não foi comprovado o fornecimento gratuito, suficiente e periódico de EPI.'),
 'r012': ('Os funcionários da manipulação estavam paramentados e realizam higiene das mãos antes da manipulação.', 'Havia funcionário da manipulação sem paramentação adequada ou sem higiene das mãos antes da manipulação.'),
 'r014': ('Os manipuladores das substâncias do Anexo III são submetidos a exames médicos específicos.', 'Os manipuladores das substâncias do Anexo III não são submetidos a exames médicos específicos.'),
 'r015': ('Os responsáveis pelo PCMSO foram comunicados da manipulação das substâncias do Anexo III.', 'Os responsáveis pelo PCMSO não foram comunicados da manipulação das substâncias do Anexo III.'),
 'n001': ('Foram apresentados os ASO admissionais dos funcionários amostrados.', 'Não foram apresentados ASO admissionais de funcionários amostrados.'),
 'n002': ('Os ASO periódicos estão dentro da periodicidade do PCMSO.', 'Há ASO periódico fora da periodicidade definida no PCMSO.'),
 'n003': ('Os ASO atestam aptidão para a função exercida.', 'Há ASO que não atesta aptidão para a função efetivamente exercida.'),
 'n004': ('Os ASO de quem manipula substâncias do Anexo III contemplam os exames específicos.', 'Os ASO de quem manipula substâncias do Anexo III não contemplam os exames específicos.'),
 # Resíduos
 'r183': ('Apresentou PGRSS compatível com as atividades e os resíduos gerados.', 'Não apresentou PGRSS compatível com as atividades e os resíduos gerados.'),
 'r186': ('Apresentou cadastro de gerador de resíduos.', 'Recomenda-se apresentar o cadastro de gerador de resíduos.'),
 'n010': ('A coleta e a destinação são feitas por empresa licenciada, com comprovantes.', 'Não foram apresentados comprovantes de coleta e destinação por empresa licenciada.'),
 'n011': ('Os resíduos químicos (hormônios, antimicrobianos, citostáticos e demais do art. 59) são segregados e destinados como Grupo B.', 'Os resíduos químicos (hormônios, antimicrobianos, citostáticos e demais do art. 59) não são segregados e destinados como Grupo B.'),
 'n012': ('Insumos e produtos vencidos, reprovados ou devolvidos aguardam descarte segregados e identificados.', 'Havia insumos ou produtos vencidos, reprovados ou devolvidos sem segregação e identificação.'),
 'n013': ('O lixo da manipulação é esvaziado fora da área de manipulação.', 'O lixo da manipulação é esvaziado dentro da área de manipulação.'),
 'r056': ('O DML está identificado, com materiais de limpeza armazenados em local específico.', 'O DML não está identificado ou os materiais de limpeza não estão armazenados em local específico.'),
 'n014': ('Os saneantes em uso são regularizados na Anvisa.', 'Havia saneante em uso sem regularização na Anvisa.'),
 'n015': ('Há local para lavagem dos materiais de limpeza.', 'Não há local para lavagem dos materiais de limpeza.'),
 'n016': ('O abrigo temporário de resíduos é identificado, de acesso restrito, lavável e com coletores tampados.', 'O abrigo temporário de resíduos não atende às condições de identificação, acesso restrito, superfícies laváveis e coletores tampados.'),
 # Áreas físicas
 'r030': ('A dispensação dispõe de local organizado para guarda das preparações, protegido do calor, da umidade e da luz.', 'O local de guarda das preparações na dispensação não é organizado ou não é protegido do calor, da umidade e da luz.'),
 'r031': ('As preparações com substâncias sob controle especial são mantidas em armário ou sala com chave.', 'Havia preparações com substâncias sob controle especial fora de armário ou sala com chave.'),
 'r032': ('A licença sanitária, a AFE e a AE estão afixadas em local visível.', 'A licença sanitária, a AFE e/ou a AE não estão afixadas em local visível.'),
 'r033': ('Os produtos expostos à venda estavam dentro do prazo de validade.', 'Havia produto exposto à venda com prazo de validade expirado.'),
 'r034': ('Não há exposição de manipulados com fim de propaganda.', 'Há exposição ao público de produtos manipulados com fim de propaganda, publicidade ou promoção.'),
 'r037': ('Os produtos termolábeis estão estocados adequadamente, com registro de temperatura.', 'Os produtos termolábeis não estão estocados adequadamente ou não há registro de temperatura.'),
 'r038': ('Há área para segregação de produtos violados, vencidos ou suspeitos, identificados.', 'Não há área para segregação de produtos violados, vencidos ou suspeitos.'),
 'r039': ('Os medicamentos sob prescrição estão em área de circulação restrita.', 'Há medicamentos sob prescrição em área de livre acesso ao público.'),
 'r040': ('A lista de medicamentos genéricos está disponível em local visível.', 'A lista de medicamentos genéricos não está disponível em local visível.'),
 'r041': ('Os medicamentos sob controle especial são guardados em sistema segregado com chave, sob guarda do farmacêutico.', 'Os medicamentos sob controle especial não são guardados em sistema segregado com chave.'),
 'r044': ('A sala de serviços dispõe de lavatório e itens de higiene exigidos.', 'A sala de serviços não dispõe de lavatório ou dos itens de higiene exigidos.'),
 'r045': ('Os materiais de primeiros socorros estão identificados e acessíveis.', 'Os materiais de primeiros socorros não estão identificados ou acessíveis.'),
 'r046': ('Os aparelhos de medição de parâmetros fisiológicos são regularizados e calibrados.', 'Há aparelho de medição de parâmetros fisiológicos sem regularização ou calibração.'),
 'r047': ('Há recipiente adequado para perfurocortantes.', 'Não há recipiente adequado para perfurocortantes.'),
 'r048': ('Há declaração de serviços farmacêuticos em duas vias, preenchida.', 'Não há declaração de serviços farmacêuticos em duas vias, devidamente preenchida.'),
 'r049': ('Há registros atualizados de limpeza da sala de serviços.', 'Não há registros atualizados de limpeza da sala de serviços.'),
 'r050': ('Apresentou registros de imunização dos profissionais que aplicam injetáveis.', 'Recomenda-se apresentar os registros de imunização dos profissionais que aplicam injetáveis.'),
 'r051': ('Há lista atualizada dos estabelecimentos públicos de saúde próximos.', 'Não há lista atualizada dos estabelecimentos públicos de saúde próximos.'),
 'r057': ('Os sanitários são de fácil acesso, sem comunicação direta com armazenamento, manipulação e controle de qualidade.', 'Os sanitários têm comunicação direta com áreas de armazenamento, manipulação ou controle de qualidade.'),
 'r058': ('Os sanitários dispõem de toalha descartável, detergente líquido e lixeira com pedal e tampa.', 'Os sanitários não dispõem de todos os itens de higiene exigidos.'),
 'r059': ('A farmácia dispõe de vestiário para guarda de pertences e troca de uniformes.', 'A farmácia não dispõe de vestiário para guarda de pertences e troca de uniformes.'),
 'n020': ('O vestiário tem armários e é separado das áreas de manipulação.', 'O vestiário não tem armários ou não é separado das áreas de manipulação.'),
 'n021': ('A copa é separada dos demais ambientes.', 'A copa não é separada dos demais ambientes.'),
 'n022': ('A geladeira da copa é de uso exclusivo para alimentos.', 'A geladeira da copa guardava medicamentos, insumos ou amostras junto com alimentos.'),
 'n023': ('A área de descanso é separada e não é usada para guarda de materiais.', 'A área de descanso não é separada ou é usada para guarda de materiais.'),
 # Almoxarifado
 'r078': ('O almoxarifado tem acesso restrito e capacidade suficiente para estocagem ordenada.', 'O almoxarifado não tem acesso restrito ou capacidade suficiente para estocagem ordenada.'),
 'r079': ('O almoxarifado é limpo e seco, com temperatura e umidade monitoradas e registradas.', 'O almoxarifado não tem temperatura e umidade monitoradas e registradas, ou não é mantido limpo e seco.'),
 'r080': ('Os materiais estão afastados do piso, das paredes e do teto.', 'Havia materiais encostados no piso, nas paredes ou no teto.'),
 'r081': ('As matérias-primas estão dentro da validade e identificadas quanto à situação interna.', 'Havia matéria-prima vencida ou sem identificação da situação interna.'),
 'r082': ('Há área segregada e identificada para quarentena.', 'Não há área segregada e identificada para quarentena.'),
 'r252': ('Os materiais recebidos permanecem em quarentena até a liberação pelo controle de qualidade.', 'Materiais recebidos são usados antes da liberação pelo controle de qualidade.'),
 'r083': ('Há área segregada e identificada para reprovados, devolvidos ou vencidos.', 'Não há área segregada e identificada para reprovados, devolvidos ou vencidos.'),
 'r084': ('Os materiais reprovados no recebimento são segregados e devolvidos.', 'Os materiais reprovados no recebimento não são segregados e devolvidos.'),
 'r085': ('Há armário ou sala com chave para substâncias sob controle especial.', 'Não há armário ou sala com chave para substâncias sob controle especial.'),
 'r086': ('As SBIT e matérias-primas sujeitas a diluição estão em local distinto, de acesso restrito e identificadas.', 'As SBIT e matérias-primas sujeitas a diluição não estão em local distinto, de acesso restrito.'),
 'r187': ('Apresentou as licenças exigidas para produtos químicos controlados.', 'Não apresentou as licenças exigidas para produtos químicos controlados.'),
 'r254': ('As FDS dos produtos químicos estão disponíveis no local de uso.', 'As FDS dos produtos químicos não estão disponíveis no local de uso.'),
 'r087': ('Há local seguro para inflamáveis, cáusticos, corrosivos e explosivos.', 'Não há local seguro para inflamáveis, cáusticos, corrosivos e explosivos.'),
 'r090': ('Há cadastro de fornecedores.', 'Não há cadastro de fornecedores.'),
 'r091': ('Há controle de estoque das matérias-primas com registro de entradas e saídas.', 'Não há controle de estoque das matérias-primas com registro de entradas e saídas.'),
 'r092': ('Há área específica para lavagem de embalagens e utensílios.', 'Não há área específica para lavagem de embalagens e utensílios.'),
 'r093': ('Há procedimentos de lavagem que previnem contaminação cruzada.', 'Não há procedimentos de lavagem que previnam contaminação cruzada.'),
 # Laboratórios
 'r060': ('A sala de paramentação é ventilada e serve de acesso às áreas de pesagem e manipulação.', 'A sala de paramentação não atende às condições exigidas (ventilação, barreira e acesso às áreas de pesagem e manipulação).'),
 'r061': ('Há lavatório exclusivo com sabonete, antisséptico e secagem das mãos.', 'Não há lavatório exclusivo com sabonete, antisséptico e secagem das mãos.'),
 'r062': ('Há EPI disponível e delimitação de área suja/limpa.', 'Não há EPI disponível ou delimitação de área suja/limpa.'),
 'r067': ('Há área ou sala específica para o controle de qualidade.', 'Não há área ou sala específica para o controle de qualidade.'),
 'r068': ('O controle de qualidade tem pessoal habilitado e está equipado para as análises exigidas.', 'O controle de qualidade não tem pessoal habilitado ou não está equipado para as análises exigidas.'),
 'r069': ('Há instalações, equipamentos e POPs para amostragem, inspeção e ensaios.', 'Não há instalações, equipamentos ou POPs para amostragem, inspeção e ensaios.'),
 'r070': ('As especificações e referências farmacopeicas estão disponíveis.', 'As especificações e referências farmacopeicas não estão disponíveis.'),
 'r071': ('As substâncias voláteis, tóxicas, corrosivas e irritantes são manipuladas em capela com exaustão.', 'Substâncias voláteis, tóxicas, corrosivas ou irritantes são manipuladas fora de capela com exaustão.'),
 'r072': ('Os solventes são armazenados conforme as orientações de segurança.', 'Os solventes não são armazenados conforme as orientações de segurança.'),
 'r073': ('A amostragem é feita em local específico, com utensílios limpos, sem risco de contaminação cruzada.', 'A amostragem não é feita em local específico ou em condições que impeçam a contaminação cruzada.'),
 'r074': ('Há área identificada e segregada para quarentena, reprovados e vencidos no controle de qualidade.', 'Não há área identificada e segregada para quarentena, reprovados e vencidos no controle de qualidade.'),
 'r075': ('A reanálise ocorre dentro da validade e comprova teor, pureza e integridade.', 'A reanálise ocorre fora da validade ou não comprova teor, pureza e integridade.'),
 'r076': ('A reprovação de insumos é notificada à autoridade sanitária.', 'A reprovação de insumos não é notificada à autoridade sanitária.'),
 'r077': ('Os equipamentos de medição e ensaio estão calibrados e identificados, com registros.', 'Há equipamento de medição ou ensaio sem calibração, identificação ou registros.'),
 'r088': ('A pesagem é feita em local específico, com exaustão e limpeza prévia das embalagens.', 'A pesagem não é feita em local específico com exaustão e limpeza prévia das embalagens.'),
 'r089': ('As embalagens das matérias-primas são limpas antes da pesagem.', 'As embalagens das matérias-primas não são limpas antes da pesagem.'),
 'r095': ('A sala é totalmente segregada dos demais laboratórios.', 'A sala não é totalmente segregada dos demais laboratórios.'),
 'r096': ('Há balança com capacidade e sensibilidade compatíveis, com procedimentos contra contaminação.', 'Não há balança com capacidade e sensibilidade compatíveis ou procedimentos contra contaminação.'),
 'r097': ('Os utensílios são diferenciados e identificados para uso interno e externo.', 'Os utensílios não são diferenciados e identificados para uso interno e externo.'),
 'r098': ('As matérias-primas estão dentro da validade e identificadas.', 'Havia matéria-prima vencida ou sem identificação.'),
 'r099': ('As matérias-primas diluídas e concentradas têm os alertas exigidos.', 'Há matéria-prima diluída ou concentrada sem os alertas exigidos.'),
 'r100': ('A água purificada em uso está identificada, com menos de 24 horas e recipiente sanitizado.', 'A água purificada em uso não está identificada, excede 24 horas ou o recipiente não é sanitizado a cada troca.'),
 'r101': ('A sala tem temperatura e umidade compatíveis, monitoradas e registradas.', 'A sala não tem temperatura e umidade monitoradas e registradas.'),
 'r102': ('A sala é totalmente segregada dos demais laboratórios.', 'A sala não é totalmente segregada dos demais laboratórios.'),
 'r103': ('Há sistema de exaustão qualificado e em funcionamento nas etapas com pós.', 'Não há sistema de exaustão qualificado e em funcionamento nas etapas com pós.'),
 'r104': ('Há balança com capacidade e sensibilidade compatíveis, com procedimentos contra contaminação.', 'Não há balança com capacidade e sensibilidade compatíveis ou procedimentos contra contaminação.'),
 'r105': ('Os utensílios são diferenciados e identificados para uso interno e externo.', 'Os utensílios não são diferenciados e identificados para uso interno e externo.'),
 'r106': ('As matérias-primas estão dentro da validade e identificadas.', 'Havia matéria-prima vencida ou sem identificação.'),
 'r107': ('As matérias-primas diluídas e concentradas têm os alertas exigidos.', 'Há matéria-prima diluída ou concentrada sem os alertas exigidos.'),
 'r108': ('Os excipientes são padronizados com embasamento técnico.', 'Os excipientes não são padronizados com embasamento técnico.'),
 'r110': ('A sala tem temperatura e umidade compatíveis, monitoradas e registradas.', 'A sala não tem temperatura e umidade monitoradas e registradas.'),
 'r111': ('Os utensílios para hormônios, antibióticos e citostáticos são separados e identificados por classe.', 'Os utensílios para hormônios, antibióticos e citostáticos não são separados e identificados por classe.'),
 'r112': ('Há armário ou sala com dispositivo de segurança para matérias-primas sob controle especial.', 'Não há armário ou sala com dispositivo de segurança para matérias-primas sob controle especial.'),
 'r243': ('Os utensílios para substâncias sob controle especial são exclusivos e identificados.', 'Os utensílios para substâncias sob controle especial não são exclusivos e identificados.'),
 # SBIT
 'r156': ('A licença sanitária permite a manipulação de SBIT, com inspeção prévia aprovada.', 'Manipula SBIT sem permissão na licença sanitária ou sem inspeção prévia aprovada.'),
 'r157': ('As SBIT manipuladas constam da lista do Anexo II.', 'Há SBIT manipulada que não consta da lista do Anexo II.'),
 'r158': ('A aquisição de SBIT é precedida de qualificação de fornecedores.', 'A aquisição de SBIT não é precedida de qualificação de fornecedores.'),
 'r159': ('As SBIT recebem identificação especial no recebimento.', 'As SBIT não recebem identificação especial no recebimento.'),
 'r160': ('As SBIT são armazenadas em local distinto, de acesso restrito, sob guarda do farmacêutico.', 'As SBIT não são armazenadas em local distinto, de acesso restrito, sob guarda do farmacêutico.'),
 'r161': ('Há dupla checagem da pesagem para manipulação de SBIT, com registro.', 'Não há dupla checagem registrada na pesagem para manipulação de SBIT.'),
 'r162': ('O encapsulamento de SBIT usa cápsulas do menor tamanho compatível.', 'O encapsulamento de SBIT não usa cápsulas do menor tamanho compatível.'),
 'r163': ('A homogeneização de SBIT segue excipientes e metodologia do perfil de dissolução.', 'A homogeneização de SBIT não segue os excipientes e a metodologia do perfil de dissolução.'),
 'r164': ('Apresentou perfil de dissolução para os sólidos com cada SBIT.', 'Não apresentou perfil de dissolução para os sólidos com SBIT.'),
 'r165': ('Os excipientes para SBIT são padronizados conforme compêndios oficiais.', 'Os excipientes para SBIT não são padronizados conforme compêndios oficiais.'),
 'r166': ('A dispensação de SBIT é acompanhada de bula simplificada.', 'A dispensação de SBIT não é acompanhada de bula simplificada.'),
 'r167': ('A dispensação de SBIT ocorre com atenção farmacêutica.', 'A dispensação de SBIT não ocorre com atenção farmacêutica.'),
 'r168': ('Há dupla checagem na pesagem para diluição de SBIT, com registro.', 'Não há dupla checagem registrada na pesagem para diluição de SBIT.'),
 'r169': ('A diluição de SBIT emprega diluição geométrica com excipientes padronizados.', 'A diluição de SBIT não emprega diluição geométrica com excipientes padronizados.'),
 'r170': ('As SBIT diluídas têm os alertas “concentrado”/“diluído”.', 'Há SBIT diluída sem os alertas “concentrado”/“diluído”.'),
 'r171': ('Há análise de teor de cada diluído de SBIT e monitoramento trimestral.', 'Não há análise de teor dos diluídos de SBIT ou monitoramento trimestral.'),
 'r172': ('Há análise completa trimestral de formulação com SBIT, em rodízio.', 'Não há análise completa trimestral de formulação com SBIT.'),
 'r173': ('Há POP do monitoramento de SBIT e os resultados são arquivados por 2 anos.', 'Não há POP do monitoramento de SBIT ou os resultados não são arquivados por 2 anos.'),
 'r174': ('Resultados insatisfatórios de SBIT geram medidas avaliadas por nova análise.', 'Resultados insatisfatórios de SBIT não geram medidas avaliadas por nova análise.'),
 # Sensibilizantes
 'r119': ('Há sala dedicada à classe, com antecâmara.', 'Não há sala dedicada à classe, com antecâmara.'),
 'r120': ('As salas têm pressão negativa em relação às áreas adjacentes.', 'As salas não têm pressão negativa em relação às áreas adjacentes.'),
 'r121': ('A pesagem dos sensibilizantes é feita na respectiva sala, com procedimentos contra contaminação cruzada.', 'A pesagem dos sensibilizantes não é feita na respectiva sala.'),
 'r122': ('Balanças e bancada são limpas antes e após cada pesagem.', 'Balanças e bancada não são limpas antes e após cada pesagem.'),
 'r123': ('Os utensílios são separados e identificados por classe terapêutica.', 'Os utensílios não são separados e identificados por classe terapêutica.'),
 'r124': ('É assegurado o uso de EPI apropriado.', 'Não é assegurado o uso de EPI apropriado.'),
 'r125': ('Há POP específico contra contaminação cruzada.', 'Não há POP específico contra contaminação cruzada.'),
 'r126': ('Os excipientes são padronizados conforme compêndios oficiais.', 'Os excipientes não são padronizados conforme compêndios oficiais.'),
}
CABINE = {
 'sala': ('Há sala dedicada, com antecâmara.', 'Não há sala dedicada, com antecâmara.'),
 'pressao': ('A sala tem pressão negativa e sistema de ar independente.', 'A sala não tem pressão negativa ou sistema de ar independente comprovado.'),
 'mp': ('As matérias-primas estão dentro da validade, correspondem à classe e estão identificadas.', 'Havia matéria-prima vencida, de outra classe ou sem identificação.'),
 'guarda': ('As matérias-primas estão em local de acesso restrito, sob guarda do farmacêutico.', 'As matérias-primas não estão em local de acesso restrito, sob guarda do farmacêutico.'),
 'uten': ('Os utensílios e placas encapsuladoras são exclusivos e identificados.', 'Os utensílios e placas encapsuladoras não são exclusivos e identificados.'),
 'transp': ('O transporte de utensílios sujos à lavagem previne contaminação cruzada.', 'O transporte de utensílios sujos à lavagem não previne contaminação cruzada.'),
 'dupla': ('Há dupla checagem da pesagem, com registro.', 'Não há dupla checagem registrada na pesagem.'),
}
for base in (127, 134, 141):
    for i, k in enumerate(['sala', 'pressao', 'mp', 'guarda', 'uten', 'transp', 'dupla']):
        F['r%03d' % (base + i)] = CABINE[k]
F.update({
 # Homeopatia
 'r148': ('Há sala exclusiva para homeopatia, em área adequada.', 'Não há sala exclusiva para homeopatia.'),
 'r149': ('As tinturas-mãe e matrizes estão identificadas e dentro da validade.', 'Há tintura-mãe ou matriz sem identificação ou fora da validade.'),
 'r150': ('Há alcoômetro e balança exclusiva, calibrados.', 'Não há alcoômetro e/ou balança exclusiva calibrados.'),
 'r151': ('Há local de lavagem e inativação com estufa e registros.', 'Não há local de lavagem e inativação com estufa e registros.'),
 'r152': ('O preparo dos álcoois tem identificação e registros de rastreabilidade.', 'O preparo dos álcoois não tem identificação ou registros de rastreabilidade.'),
 'r153': ('Foram apresentados os ensaios dos insumos homeopáticos.', 'Não foram apresentados os ensaios dos insumos homeopáticos.'),
 'r154': ('As matrizes dinamizadas têm registros de rastreabilidade.', 'As matrizes dinamizadas não têm registros de rastreabilidade.'),
 'r155': ('O preparo de auto-isoterápicos atende às exigências de sala, inativação e biossegurança.', 'O preparo de auto-isoterápicos não atende às exigências de sala, inativação e biossegurança.'),
 'r236': ('As matrizes e insumos homeopáticos têm identificação e rastreabilidade.', 'As matrizes e insumos homeopáticos não têm identificação e rastreabilidade.'),
 'r237': ('As matrizes estão estocadas em álcool a 77% (v/v) ou superior.', 'Há matriz estocada em álcool abaixo de 77% (v/v).'),
 # Exaustão
 'r114': ('Apresentou Qualificação de Projeto do sistema de exaustão.', 'Não apresentou Qualificação de Projeto do sistema de exaustão.'),
 'r115': ('Apresentou Qualificação de Instalação do sistema de exaustão.', 'Não apresentou Qualificação de Instalação do sistema de exaustão.'),
 'r116': ('Apresentou Qualificação de Operação do sistema de exaustão.', 'Não apresentou Qualificação de Operação do sistema de exaustão.'),
 'r117': ('Apresentou Qualificação de Desempenho do sistema de exaustão.', 'Não apresentou Qualificação de Desempenho do sistema de exaustão.'),
 'r118': ('A qualificação do sistema de exaustão está vigente.', 'A qualificação do sistema de exaustão está vencida ou sem requalificação/manutenção no prazo.'),
 # Receitas
 'r208': ('As prescrições amostradas atendem à avaliação farmacêutica e à legislação específica.', 'Há prescrição amostrada em desacordo com a avaliação farmacêutica ou a legislação específica.'),
 'r209': ('As prescrições são legíveis, sem rasuras, com identificação do prescritor e do paciente.', 'Há prescrição ilegível, rasurada ou sem identificação do prescritor ou do paciente.'),
 'r210': ('As prescrições identificam substância, concentração, forma, quantidade, posologia, data e assinatura.', 'Há prescrição sem todos os dados exigidos da formulação, da posologia, da data ou da assinatura.'),
 'r211': ('Os cálculos de manipulação são realizados e registrados na ordem de manipulação.', 'Os cálculos de manipulação não são registrados na ordem de manipulação.'),
 'n030': ('As ordens de manipulação correspondem às prescrições.', 'Há ordem de manipulação que não corresponde à prescrição.'),
 'r054': ('Há procedimento de conferência da ordem de manipulação frente à prescrição.', 'Não há procedimento de conferência da ordem de manipulação frente à prescrição.'),
 'r053': ('O farmacêutico avalia os ensaios, aprova a dispensação e assina a ordem de manipulação.', 'O farmacêutico não avalia os ensaios, não aprova a dispensação ou não assina a ordem de manipulação.'),
 'r215': ('As assinaturas eletrônicas são verificadas e os arquivos digitais conservados.', 'As assinaturas eletrônicas não são verificadas ou os arquivos digitais não são conservados.'),
 'r213': ('As prescrições de controlados atendem à legislação específica.', 'Há prescrição de controlado em desacordo com a legislação específica.'),
 'r214': ('A dispensação de antimicrobianos observa prazo, retenção e registro.', 'A dispensação de antimicrobianos não observa prazo, retenção ou registro.'),
 'r043': ('Apresentou certificado de transmissão regular do SNGPC.', 'Não apresentou certificado de transmissão regular do SNGPC.'),
 'r042': ('O estoque físico de medicamentos controlados confere com o escriturado.', 'Há divergência entre o estoque físico e o escriturado de medicamentos controlados.'),
 'r113': ('O estoque físico de insumos controlados confere com o escriturado.', 'Há divergência entre o estoque físico e o escriturado de insumos controlados.'),
 'r189': ('Apresentou comprovantes de envio dos mapas e balanços da Portaria 344/98.', 'Não apresentou comprovantes de envio dos mapas e balanços da Portaria 344/98.'),
 'r198': ('Há Livro de Receituário (ou sistema) com termos de abertura e encerramento.', 'Não há Livro de Receituário (ou sistema) com termos de abertura e encerramento.'),
 'r199': ('Apresentou autorização de informatização dos livros.', 'Não apresentou autorização de informatização dos livros.'),
 'r036': ('A dispensação de preparações sob controle especial atende à legislação específica.', 'Há dispensação de preparação sob controle especial em desacordo com a legislação específica.'),
 'r241': ('As receitas aviadas são carimbadas com identificação, data e número de registro.', 'Há receita aviada sem carimbo com identificação, data e número de registro.'),
 'r242': ('A repetição de receita está amparada na duração indicada ou em confirmação registrada do prescritor.', 'Há repetição de receita sem duração indicada e sem confirmação registrada do prescritor.'),
 'n050': ('Não foi constatada manipulação em substituição a medicamento industrializado prescrito.', 'Foi constatada manipulação de preparação em substituição a medicamento industrializado prescrito.'),
 'n051': ('A transformação de especialidade farmacêutica, quando ocorre, é excepcional e justificada tecnicamente.', 'Há transformação de especialidade farmacêutica fora das hipóteses excepcionais ou sem justificativa técnica.'),
 'n031': ('A dispensação é feita com orientação farmacêutica.', 'A dispensação não é feita com orientação farmacêutica.'),
 # Monitoramento
 'r203': ('Há POP de amostragem e periodicidade das análises de água.', 'Não há POP de amostragem e periodicidade das análises de água.'),
 'r204': ('Um dos pontos de amostragem da água purificada é o local de armazenamento.', 'O local de armazenamento da água purificada não é ponto de amostragem.'),
 'r207': ('Laudos insatisfatórios da água purificada geram medidas avaliadas por nova análise.', 'Laudos insatisfatórios da água purificada não geram medidas registradas e avaliadas por nova análise.'),
 'r205': ('As análises da água potável contemplam todos os parâmetros exigidos.', 'As análises da água potável não contemplam todos os parâmetros exigidos.'),
 'r206': ('Laudos insatisfatórios da água potável geram medidas registradas.', 'Laudos insatisfatórios da água potável não geram medidas registradas.'),
 'r194': ('Há contrato vigente com o laboratório que realiza as análises do monitoramento.', 'Não há contrato vigente com o laboratório que realiza as análises do monitoramento.'),
 'n052': ('Há POP do monitoramento com cronograma das análises.', 'Não há POP do monitoramento com cronograma das análises.'),
 'n053': ('As amostras seguem sistema de rodízio de manipuladores, fármacos e dosagens.', 'As amostras não seguem sistema de rodízio de manipuladores, fármacos e dosagens.'),
 'r250': ('O laboratório das análises é licenciado e habilitado na REBLAS.', 'O laboratório das análises não é licenciado ou habilitado na REBLAS.'),
 # Venda remota e transporte
 'n041': ('Possui licença sanitária para a venda remota.', 'Realiza venda remota sem licença sanitária para a atividade.'),
 'n042': ('Apresentou POP de venda remota.', 'Não apresentou POP de venda remota.'),
 'n043': ('A venda remota de controlados/antimicrobianos segue a legislação.', 'A venda remota de controlados/antimicrobianos não segue a legislação.'),
 'r238': ('Há procedimentos escritos de conservação e transporte.', 'Não há procedimentos escritos de conservação e transporte.'),
 'r239': ('Os termossensíveis são mantidos e transportados em temperatura compatível.', 'Os termossensíveis não são mantidos ou transportados em temperatura compatível.'),
 'r240': ('Os manipulados não são armazenados ou transportados com materiais incompatíveis.', 'Os manipulados são armazenados ou transportados com materiais incompatíveis.'),
 'n044': ('A entrega preserva as condições do produto.', 'A entrega não preserva as condições do produto.'),
})
